#version: '3.8'
services:
    speedtest:
        image: index.docker.io/openspeedtest/latest:latest
        container_name: openspeedtest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - '3000:3000'
            - '3001:3001'
        volumes:
            - 'openspeedtestVol:/var/log/letsencrypt'
        networks:
            - myNUCNetwork
volumes:
    openspeedtestVol:
        name: openspeedtestVol
        external: true
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
