version: '3.8'
services:
     qbittorrent:
         image: lscr.io/linuxserver/qbittorrent:latest
         container_name: qbittorrent
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - TZ=Europe/London
             - WEBUI_PORT=8181
         ports:
             - '8181:8181'
             - '6881:6881'
             - '6881:6881/udp'
         volumes:
             - /mnt/exdisk/qbittorrent/config:/config
             - /mnt/exdisk/qbittorrent/downloads:/downloads
         networks:
             - myPiNetwork
networks:
     myPiNetwork:
         name: myPiNetwork
         external: true
