services:
  wallos:
    container_name: wallos
    image: index.docker.io/bellamy/wallos:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#    ports:
#      - 8282:80/tcp
    environment:
      TZ: Europe/London
      OIDC_ENABLED: true
      OIDC_PROVIDER_NAME: Authelia
      OIDC_CLIENT_ID: wallos
#      OIDC_CLIENT_SECRET: ${oidc_client_secret}
      OIDC_CLIENT_SECRET_FILE: /run/secrets/wallos_oidc_client_secret
      OIDC_ISSUER: https://sso.thehome.party
      OIDC_AUTH_URL: https://sso.thehome.party/api/oidc/authorization
      OIDC_TOKEN_URL: https://sso.thehome.party/api/oidc/token
      OIDC_USERINFO_URL: https://sso.thehome.party/api/oidc/userinfo
      OIDC_REDIRECT_URL: https://wallos.thehome.party/index.php
      OIDC_LOGOUT_URL: https://sso.thehome.party/logout
      OIDC_USER_IDENTIFIER: preferred_username
      OIDC_SCOPES: openid email profile
      OIDC_AUTO_CREATE_USER: false
      OIDC_DISABLE_PASSWORD_LOGIN: false
      OIDC_REQUIRE_EMAIL_VERIFIED: false
      SSRF_ALLOWLIST: sso.thehome.party
    secrets:
      - wallos_oidc_client_secret
    volumes:
      - /home/davepifive/DockerData/wallos/db:/var/www/html/db
      - /home/davepifive/DockerData/wallos/logos:/var/www/html/images/uploads/logos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallos.rule=Host(`wallos.thehome.party`)"
      - "traefik.http.routers.wallos.entrypoints=websecure"
      - "traefik.http.routers.wallos.tls=true"
      - "traefik.http.services.wallos.loadbalancer.server.port=80"
      - "glance.name=Wallos"
      - "glance.icon=sh:wallos"
      - "glance.url=https://wallos.thehome.party"
      - "glance.description=Subscription Management"
    networks:
      - default
      - traefik-internal
secrets:
  wallos_oidc_client_secret:
    file: ./secrets/wallos_oidc_client_secret
networks:
  traefik-internal:
    external: true