version: '3.8'
services:
     bookstack:
         image: lscr.io/linuxserver/bookstack:latest
         container_name: bookstack
         restart: unless-stopped
         depends_on:
             - bookstack_db
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - APP_URL=https://bookstack.thehome.party
             - DB_PORT=3306
             - DB_HOST=bookstack_db
             - DB_USER=bookstack
             - DB_PASS=yourdbpass
             - DB_DATABASE=bookstackapp
         volumes:
             - bookstackAppVol:/config
         ports:
             - '6875:80'
         networks:
             - myNUCNetwork
     bookstack_db:
         image: lscr.io/linuxserver/mariadb:latest
         container_name: bookstack_db
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - MYSQL_ROOT_PASSWORD=yourdbrootpass
             - TZ=Europe/London
             - MYSQL_DATABASE=bookstackapp
             - MYSQL_USER=bookstack
             - MYSQL_PASSWORD=yourdbpass
         volumes:
             - bookstackDBVol:/config
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork: 
         name: myNUCNetwork 
         external: true
volumes:
     bookstackAppVol:
         name: bookstackAppVol
         external: true
     bookstackDBVol:
         name: bookstackDBVol
         external: true
