version: "3.8"
services:
  dashy:
    image: index.docker.io/lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    user: 1000:1000
    #  - UID=1000
    #  - GID=1000
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
    #   - /home/dave/dashy/my-local-conf.yml:/app/public/conf.yml
        - dashyVol:/app/public/ #file needs to be conf.yml
    ports:
        - '4000:80'
    networks:
        - myNUCNetwork
    labels:
        #- "traefik.port=4000"
        - "traefik.http.services.dashy.loadbalancer.server.port=4000"
        - "traefik.http.routers.dashy.rule=Host(`dashy.nuc.main`)"
    # Set any environmental variables
    #environment:
    #  - NODE_ENV=production
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
    myNUCNetwork: 
        name: myNUCNetwork 
        external: true
volumes:
    dashyVol:
        name: dashyVol
        external: true
