version: "3.8"
services:
  dashy:
    image: index.docker.io/lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
        - '/home/dave/dashy/conf.yml:/app/public'
        #- './certs/privkey1.pem:/etc/ssl/certs/dashy-priv.key'
        #- './certs/cert1.pem:/etc/ssl/certs/dashy-pub.pem'
        #- dashyVol:/app/public/ #file needs to be conf.yml
        #- dashyVol:/etc/ssl/certs/ #to upload ssl certs
    ports:
        - '4000:80' #no longer required, accessing via https
        - '4001:443'
    networks:
        - myNUCNetwork
    #labels:
        #- "traefik.port=4000"
        #- "traefik.http.services.dashy.loadbalancer.server.port=4000"
        #- "traefik.http.routers.dashy.rule=Host(`nuc.main`)"
        #- "traefik.docker.network=myNUCNetwork"
    # Set any environmental variables
    environment:
       #- url=http://dashy.nuc.main/
        #- NODE_ENV=production
      # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
        - 'UID=1000'
        - 'GID=1000'
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
    myNUCNetwork: 
        name: myNUCNetwork 
        external: true
#volumes no longer needed, using bind mounts for three files instead
#volumes:
#    dashyVol:
#        name: dashyVol
#        external: true
