version: "3.8"
services:
     grafana:
         image: index.docker.io/grafana/grafana-enterprise:latest
         container_name: grafana
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         #user: 1000:1000
         #environment:
             #- UID=1000
             #- GID=1000
             #- GF_SERVER_ROOT_URL=http://my.grafana.server/
             #- GF_INSTALL_PLUGINS=grafana-clock-panel
         ports:
             - '3000:3000'
         volumes:
             - grafanaVol:/var/lib/grafana #path for data 
             #- grafanaVol:/etc/grafana #grafana.ini file is here
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork 
         external: true
volumes:
     grafanaVol:
         name: grafanaVol
         external: true
