version: '3.8'
services:
     npm:
         image: index.docker.io/jc21/nginx-proxy-manager:latest
         container_name: npm
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         ports:
             - '80:80'
             - '81:81'
             - '443:443'
         volumes:
             - npmVol:/data
             - npmVol:/etc/letsencrypt
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
volumes:
     npmVol:
         name: npmVol
         external: true
