version: '3.8'
services:
    speedtest:
        image: index.docker.io/openspeedtest/latest:latest
        container_name: openspeedtest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - '3000:3000'
            - '3001:3001'
        networks:
            - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
