version: '3.8'
services:
     portainer-ce:
         image: portainer/portainer-ce:latest
         container_name: portainer
         security_opt:
             - no-new-privileges:true
         restart: unless-stopped
         ports:
             - '9000:9000'
             - '8000:8000'
             - '9443:9443'
         volumes:
             - '/var/run/docker.sock:/var/run/docker.sock'
             - 'portainerVol:/data'
         networks:
             - myNUCNetwork
volumes:
         portainerVol:
             name: portainerVol
             external: true
networks:
         myNUCNetwork:
             name: myNUCNetwork
             external: true