version: '3.8'
services:
     syslog-ng:
         image: lscr.io/linuxserver/syslog-ng:latest
         container_name: syslog-ng
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         #user: 1000:1000
         environment:
             - PUID=1000
             - PGID=1000
         ports:
             - 514:5514/udp
             - 601:6601/tcp
             - 6514:6514/tcp
         volumes:
             - syslog-ngVol:/config
             - syslog-ngVol:/var/log #optional
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork 
         external: true
volumes:
     syslog-ngVol:
         name: syslog-ngVol
         external: true