#version: '3.8'
services:
     caddy:
         image: index.docker.io/caddy:latest
         container_name: caddy
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - TZ=Europe/London
         ports:
             - '85:80'
             - '4443:443'
         volumes:
             - caddyVol:/etc/caddy/
             #- caddyVol/data:/data/
             #- caddyVol/config:/config/
         networks:
            # - myNUCIntNetwork #check network
             - myNUCNetwork
networks:
     #myNUCIntNetwork: #check network
     #    name: myNUCIntNetwork #check network
     #    internal: true
     myNUCNetwork:
         name: myNUCNetwork
         external: true
volumes:
     caddyVol:
         name: caddyVol
         external: true
