#version: "3.8"
services:
    dufs:
        image: index.docker.io/sigoden/dufs:latest
        container_name: dufs
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        environment:
            - UID=1000
            - GID=1000
#            - DUFS_TLS_CERT='/home/dave/certs/cert1.pem'
#            - DUFS_TLS_KEY='/home/dave/certs/privkey1.pem'
        volumes:
            - '/home/dave/dufs/data:/data'
        command: /data -A # --tls-cert '/home/dave/certs/cert1.pem' --tls-key '/home/dave/certs/privkey1.pem'
        ports:
            - '5000:5000'
        networks:
            - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
