#version: "3.8"
services:
     crontab-ui:
         image: index.docker.io/alseambusher/crontab-ui:latest
         container_name: crontab-ui
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
#         user: 1000:1000
         ports:
             - '8090:8000'
         volumes:
             - /home/dave/crontab-ui:/crontab-ui/crontabs #path for data 
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
