{
 "title": "Softsensor Single Sensor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server_instance",
    "label": "Instance",
    "query": "label_values(corelight_monitor_pkts_link_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(corelight_monitor_conns_tcp_active{instance=~\"[[server_instance]]\"})",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(corelight_monitor_conns_udp_active{instance=~\"[[server_instance]]\"})",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(corelight_monitor_conns_icmp_active{instance=~\"[[server_instance]]\"})",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "Suricata Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "corelight_suricata_rules_loaded{instance=~\"[[server_instance]]\"}",
     "legendFormat": "Rules Loaded"
    },
    {
     "expr": "corelight_suricata_rules_failed{instance=~\"[[server_instance]]\"}",
     "legendFormat": "Rules Failed"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "corelight_filesystem_usage_ratio{instance=~\"[[server_instance]]\"}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "corelight_filesystem_size_bytes{instance=~\"[[server_instance]]\"}"
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_pkts_data_bytes_total{instance=~\"[[server_instance]]\"}[$__interval])*8)",
     "legendFormat": "Zeek"
    },
    {
     "expr": "rate(corelight_suricata_pkts_data_bytes_total{instance=~\"[[server_instance]]\"}[$__interval]) * 8  ",
     "legendFormat": "Suricata"
    },
    {
     "expr": "rate(corelight_monitor_pkts_data_bytes_total{instance=~\"[[server_instance]]\"}[$__interval]) * 8  ",
     "legendFormat": "{{process}} rate"
    },
    {
     "expr": "sum(rate(corelight_monitor_pkts_dropped_total{instance=~\"[[server_instance]]\"}[$__interval]))",
     "legendFormat": "Dropped rate"
    }
   ]
  },
  {
   "title": "Mapped Memory Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "corelight_memory_mapped_bytes{instance=~\"[[server_instance]]\"}",
     "legendFormat": "Mapped {{process}}"
    },
    {
     "expr": "corelight_memory_allocated_bytes{instance=~\"[[server_instance]]\"}",
     "legendFormat": "Allocated {{process}}"
    }
   ]
  },
  {
   "title": "Total Memory Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(corelight_memory_allocated_bytes{instance=~\"[[server_instance]]\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(corelight_memory_mapped_bytes{instance=~\"[[server_instance]]\"})",
     "legendFormat": "Mapped"
    },
    {}
   ]
  },
  {
   "title": "Connection Information",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_conns_killed_by_inactivity_total{instance=~\"[[server_instance]]\"}[$__interval])) ",
     "legendFormat": "Killed by Inactivity"
    },
    {
     "expr": "sum(corelight_monitor_conns_fragments{instance=~\"[[server_instance]]\"})",
     "legendFormat": "Fragments"
    }
   ]
  },
  {
   "title": "New connection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_conns_tcp_total{instance=~\"[[server_instance]]\"}[$__interval])) by (job)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(corelight_monitor_conns_udp_total{instance=~\"[[server_instance]]\"}[$__interval])) by (job)",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(rate(corelight_monitor_conns_icmp_total{instance=~\"[[server_instance]]\"}[$__interval])) by (job)",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "corelight_filesystem_usage_ratio{instance=~\"[[server_instance]]\"}",
     "legendFormat": "{{job}} disk used"
    }
   ]
  }
 ]
}