#version: '3.8'
services:
    uptime-kuma:
        image: index.docker.io/elestio/uptime-kuma:latest
        container_name: uptime-kuma
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - '3001:3001'
        volumes:
            - 'uptimekumaVol:/app/data'
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - myNUCNetwork
networks:
    myNUCNetwork:
        name: myNUCNetwork
        external: true
volumes:
    uptimekumaVol:
        name: uptimekumaVol
        external: true
