services:
  duplicati:
    image: index.docker.io/duplicati/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SETTINGS_ENCRYPTION_KEY=${enc_key}
    volumes:
      - /home/davepifive/DockerData/duplicati/config:/config #config files
      - /home/davepifive/DockerData/duplicati/data:/data #config files
      #read only folders, no need to write
      - /home/davepifive/DockerData:/source/docker-data:ro
      - /home/davepifive/sqlite-snapshots-DockerData:/source/sqlite-snapshots:ro
      - /home/davepifive/scripts:/source/scripts:ro
      # directory to restore to, rather than direct to live locations
      - /home/davepifive/duplicati-restore-point:/source/restore-point
#    ports:
#      - "8200:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.thehome.party`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      - "glance.name=Duplicati"
      - "glance.icon=sh:duplicati"
      - "glance.url=https://duplicati.thehome.party"
      - "glance.description=Backups"
    healthcheck:
      test: /opt/duplicati/duplicati-server-util health
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 1m
    networks:
      - default
      - traefik-internal
networks:
  traefik-internal:
    external: true