version: '3.8'
services:
     bookstack:
         image: index.docker.io/linuxserver/bookstack:latest
         container_name: bookstack
         restart: unless-stopped
         depends_on:
             - bookstack_db
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - APP_URL=https://bookstack.thehome.party
             - DB_PORT=3306
             - DB_HOST=bookstack_db
             - DB_USER=bookstack
             - DB_PASS=yourdbpass
             - DB_DATABASE=bookstackapp
         volumes:
             - '/home/dave/bookstack/config:/config'
         ports:
             - '6875:80'
             - '6876:443'
         networks:
             - myNUCNetwork
     bookstack_db:
         image: index.docker.io/library/mariadb:latest
         container_name: bookstack_db
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         environment:
             - PUID=1000
             - PGID=1000
             - MYSQL_ROOT_PASSWORD=yourdbrootpass
             - TZ=Europe/London
             - MYSQL_DATABASE=bookstackapp
             - MYSQL_USER=bookstack
             - MYSQL_PASSWORD=yourdbpass
         volumes:
             - '/home/dave/bookstack/db/config:/config'
             - '/home/dave/bookstack/db/files:/var/lib/mysql'
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork:
         name: myNUCNetwork
         external: true
#volumes:
#     bookstackAppVol:
#     bookstackDBConfigVol:
#     bookstackDBFilesVol:
