services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
# ports not used in traefik, only in npm
# traefik uses traefik-internal network instead
#    ports:
#      - "3552:3552"
    environment:
      - TZ=Europe/London
      - APP_URL=https://arcane.thehome.party
      - PUID=1000
      - PGID=1000
      - PROJECTS_DIRECTORY=/home/davepifive/docker-compose
      - ENCRYPTION_KEY=${enc_key}
      - JWT_SECRET=${jwt}
      - DOCKER_HOST=tcp://socket-proxy-management:2375
      - OIDC_ENABLED='true'
      - OIDC_ISSUER_URL='https://sso.thehome.party'
      - OIDC_CLIENT_ID='arcane'
      - OIDC_CLIENT_SECRET=${oidc_client_secret}
      - OIDC_SCOPES='openid email profile'
      - OIDC_MERGE_ACCOUNTS='true'
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
      - /home/davepifive/DockerData/arcane/data:/app/data
      - /home/davepifive/docker-compose:/home/davepifive/docker-compose
    healthcheck:
      test: ['CMD', '/app/arcane', 'health']
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcane.rule=Host(`arcane.thehome.party`)"
      - "traefik.http.routers.arcane.entrypoints=websecure"
      - "traefik.http.routers.arcane.tls=true"
      - "traefik.http.services.arcane.loadbalancer.server.port=3552" # match Mealie's actual internal port
    networks:
      - default
      - traefik-internal
      - wollomatic-socket-proxy-management_socket-proxy-management-net
networks:
  wollomatic-socket-proxy-management_socket-proxy-management-net:
    driver: bridge
    external: true
  traefik-internal:
    external: true
