services:
  gotify:
    image: index.docker.io/gotify/server-arm64:latest
    container_name: gotify
    restart: unless-stopped
    #         user: '1000:1000'
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/London
      - GOTIFY_DEFAULTUSER_PASS=${def_usr_pass}
      - UID='1000'
      - GID='1000'
      - GOTIFY_OIDC_ENABLED=true
      - GOTIFY_OIDC_ISSUER=https://sso.thehome.party #url of authelia
      - GOTIFY_OIDC_CLIENTID=gotify
      - GOTIFY_OIDC_CLIENTSECRET=${oidc_client_secret}
      - GOTIFY_OIDC_REDIRECTURL=https://gotify.thehome.party/auth/oidc/callback
      - GOTIFY_OIDC_AUTOREGISTER=true
      - GOTIFY_OIDC_USERNAMECLAIM=preferred_username
      - GOTIFY_OIDC_LINK_BY_USERNAME=false
      - GOTIFY_OIDC_SCOPES=openid,profile,email
    volumes:
      - /home/davepifive/DockerData/gotify/data:/app/data
#    ports:
#      - 8090:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`gotify.thehome.party`)"
      - "traefik.http.routers.gotify.entrypoints=websecure"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    networks:
      - default
      - traefik-internal
networks:
  traefik-internal:
    external: true