services:
  gotify:
    image: ghcr.io/gotify/server-arm64:3.1.0
    container_name: gotify
    restart: unless-stopped
    # user: '1000:1000'
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/London
      # - GOTIFY_DEFAULTUSER_PASS=${def_usr_pass}
      - GOTIFY_DEFAULTUSER_PASS_FILE=/run/secrets/gotify_def_user_pass
      - UID='1000'
      - GID='1000'
      - GOTIFY_OIDC_ENABLED=true
      - GOTIFY_OIDC_ISSUER=https://sso.thehome.party  # url of authelia
      - GOTIFY_OIDC_CLIENTID=gotify
      # - GOTIFY_OIDC_CLIENTSECRET=${oidc_client_secret}
      - GOTIFY_OIDC_CLIENTSECRET_FILE=/run/secrets/gotify_oidc_client_secret
      - GOTIFY_OIDC_REDIRECTURL=https://gotify.thehome.party/auth/oidc/callback
      - GOTIFY_OIDC_AUTOREGISTER=true
      - GOTIFY_OIDC_USERNAMECLAIM=preferred_username
      - GOTIFY_OIDC_LINK_BY_USERNAME=false
      - GOTIFY_OIDC_SCOPES=openid,profile,email
      - GOTIFY_OIDC_IDP_NAME=Authelia
    volumes:
      - /home/davepifive/DockerData/gotify/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-internal"
      - "traefik.http.routers.gotify.rule=Host(`gotify.thehome.party`)"
      - "traefik.http.routers.gotify.entrypoints=websecure"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.routers.gotify.service=gotify-svc"
      - "traefik.http.services.gotify-svc.loadbalancer.server.port=80"
      - "glance.name=Gotify"
      - "glance.icon=sh:gotify"
      - "glance.url=https://gotify.thehome.party"
      - "glance.description=Notifications"
      # router for gotify webhooks, via cloudflare tunnel
      - "traefik.http.routers.gotify-hooks.rule=Host(`gotify-hooks.thehome.party`) && PathPrefix(`/message`)"
      - "traefik.http.routers.gotify-hooks.entrypoints=websecure"
      - "traefik.http.routers.gotify-hooks.tls=true"
      - "traefik.http.routers.gotify-hooks.service=gotify-hooks-svc"
      - "traefik.http.services.gotify-hooks-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.gotify-hooks.middlewares=crowdsec@file"
    secrets:
      - gotify_def_user_pass
      - gotify_oidc_client_secret
    networks:
      - default
      - traefik-internal
networks:
  traefik-internal:
    external: true
secrets:
  gotify_def_user_pass:
    file: /home/davepifive/DockerData/gotify/secrets/gotify_def_user_pass
  gotify_oidc_client_secret:
    file: /home/davepifive/DockerData/gotify/secrets/gotify_oidc_client_secret
