services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:latest
    container_name: tinyauth
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required if using tinyauth label discovery
    environment:
      - SECRET=wVwHXDaDH3vXDtW2ULVlQGO3U2yvTgQ3
      - APP_URL=https://tinyauth.thehome.party
      - USERS=dave:$$2a$$10$$32qSI/jdTJXUzAnT8GGMVuiyGFsk/dz5GqrgUyKw.ulDrmdFcUDQW # user:password
    networks:
      - myNUCNetwork
networks:
  myNUCNetwork:
    name: myNUCNetwork
    external: true
