services:
  dynacat:
    container_name: dynacat
    image: index.docker.io/panonim/dynacat:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/davepifive/DockerData/dynacat/config:/app/config
      - /home/davepifive/DockerData/dynacat/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - ENABLE_DYNAMIC_UPDATE=TRUE
    networks:
      - myNUCNetwork
networks:
  myNUCNetwork:
    name: myNUCNetwork
    external: true