services:
  glances:
    image: index.docker.io/nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w #web-server mode
      - TZ=Europe/London
#    networks:
#      - myNUCNetwork
#networks:
#  myNUCNetwork:
#    name: myNUCNetwork
#    external: true
