services:
  glances:
    image: index.docker.io/nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#    ports:
#      - 61208:61208
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w #web-server mode
      - TZ=Europe/London
      - DOCKER_HOST=tcp://socket-proxy-readonly-vm:2375
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:61208/api/4/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.thehome.party`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.tls=true"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.routers.glances.middlewares=authelia@docker"
    networks:
      - default
      - traefik-internal
      - wollomatic-socket-proxy_socket-proxy-readonly-wm-net
networks:
  wollomatic-socket-proxy_socket-proxy-readonly-wm-net:
    driver: bridge
    external: true
  traefik-internal:
    external: true