services:
  cloudflared:
    image: index.docker.io/cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run #don't update voa cloudflare, watchtower will do it
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TUNNEL_METRICS=0.0.0.0:60123
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "glance.name=Cloudflared"
      - "glance.icon=sh:cloudflare"
      - "glance.description=Cloudflare Tunnel"
    networks:
      - default
      - traefik-internal
networks:
  traefik-internal:
    external: true