services:
  pve-exporter:
    image: index.docker.io/prompve/prometheus-pve-exporter:latest
    container_name: pve-exporter
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9221:9221"
    volumes:
      - /home/davepifive/DockerData/pve-exporter/pve.yml:/etc/prometheus/pve.yml
    networks:
      - myNUCNetwork
networks:
  myNUCNetwork:
    name: myNUCNetwork
    external: true
