version: '3.8'
services:
     jellyfin:
         image: lscr.io/linuxserver/jellyfin:latest
         container_name: jellyfin
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         #user: 1000:1000
         environment:
             - PUID=1000
             - PGID=1000
             #- JELLYFIN_PublishedServerUrl=http://davepi.mess
         ports:
             - '8096:8096' #http
             - '8920:8920' #https
         labels:
             - traefik.http.routers.jellyfin.rule=Host(`jellyfin.davepi.mess`)
         volumes:
             #- ./config:/config
             #- ./cache:/cache
             - jellyfinVol:/config
             - jellyfinVol:/cache
             - /mnt/exdisk:/media
             - /mnt/exdisk/Movies:/data/movies
             - /mnt/exdisk/Books:/data/books
             #- /path/to/media2:/media2:ro
         networks:
             - myPiNetwork 
networks:
     myPiNetwork: 
         name: myPiNetwork 
         external: true
volumes:
     jellyfinVol:
         name: jellyfinVol
         external: true