services:
  dozzle:
    container_name: dozzle
    image: index.docker.io/amir20/dozzle:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    environment:
      - DOZZLE_NO_ANALYTICS
      - DOCKER_HOST=tcp://socket-proxy-readonly-wm:2375
      - DOZZLE_ENABLE_MCP=true
    healthcheck:
      test:
        - CMD
        - /dozzle
        - healthcheck
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - default
      - wollomatic-socket-proxy_socket-proxy-readonly-wm-net
networks:
  wollomatic-socket-proxy_socket-proxy-readonly-wm-net:
    driver: bridge
    external: true