version: '3.8'
services:
    portainer-ee:
        image: 'index.docker.io/portainer/portainer-ee:latest'
        container_name: portainer
        security_opt:
             - no-new-privileges:true
        restart: unless-stopped
        ports:
           # - '8000:8000' #only used for edge clients
           # - '9000:9000' #legacy port for mgmt web interface, portainer agent uses 9001 to speak to server
            - '9443:9443'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/home/dave/portainerBE/data:/data'
            - '/home/dave/certs/privkey1.pem:/certs/portainer.key'
            - '/home/dave/certs/fullchain1.pem:/certs/portainer.crt'
        command:
            --sslcert /certs/portainer.crt
            --sslkey /certs/portainer.key
        environment:
            - UID=1000
            - GID=1000
        networks:
            - myNUCNetwork
volumes:
         portainerBEVol:
networks:
         myNUCNetwork:
             name: myNUCNetwork
             external: true
