version: '3.8'
services:
     obsidian:
         image: 'ghcr.io/sytone/obsidian-remote:latest'
         container_name: obsidian-remote
         restart: unless-stopped
         security_opt:
             - no-new-privileges:true
         ports:
             - '8080:8080'
         volumes:
             - obsidianVol:/vaults
             - obsidianVol:/config
         networks:
             - myNUCNetwork
networks:
     myNUCNetwork: 
         name: myNUCNetwork 
         external: true
volumes:
     obsidianVol:
         name: obsidianVol
         external: true
