#version: "3.8"
services:
    memos:
        image: index.docker.io/neosmemo/memos:latest
        container_name: memos
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        user: '1000:1000'
        environment:
            - PUID='1000'
            - PGID='1000'
        ports:
            - '5230:5230'
        volumes:
            - '/home/dave/memos/data:/var/opt/memos'
        networks:
            - myNUCNetwork
networks:
    myNUCNetwork:
        name: myNUCNetwork
        external: true
