version: "3.8"
services:
  dashy:
    image: index.docker.io/lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
#    user: 1000:1000
    security_opt:
        - no-new-privileges:true
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
        - '/home/dave/docker-compose/dashy/conf.yml:/app/user-data/conf.yml'
        #SSL certs are required to enable the HTTPS server on port 4001:443, even though accessing via reverse proxy
        - '/home/dave/certs/privkey1.pem:/etc/ssl/certs/dashy-priv.key'
        - '/home/dave/certs/cert1.pem:/etc/ssl/certs/dashy-pub.pem'
        #- dashyVol:/app/public/ #file needs to be conf.yml
        #- dashyVol:/etc/ssl/certs/ #to upload ssl certs
    ports:
        - '4000:8080' #no longer required, accessing via https
        - '4001:443'
    networks:
        - myNUCNetwork
    # Set any environmental variables
    environment:
        - BASE_URL=https://dashy.thehome.party/
        - NODE_ENV=development
       #Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
        - IS_DOCKER=true
        - REDIRECT_HTTPS=true
        - UID=1000
        - GID=1000
    #Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
    myNUCNetwork:
        name: myNUCNetwork
        external: true
#volumes no longer needed, using bind mounts for three files instead
#volumes:
#    dashyVol:
#        name: dashyVol
#        external: true
